server.port: 2505
application:
  title: Mono statistic
  version: 0.0.1

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  cache:
    type: simple

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.logging.LoggingAutoConfiguration


client:
  mono:
    auth-token: ${MONO_AUTH_TOKEN}

mono:
  accounts:
    cache:
      ttlInMinutes: 120
  statement:
    startDateUnix: 1640995200 # 2022-01-01
  statistic:
    supportedCardType:
      - black
      - white

