server.port: 2505

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    locations: classpath:db/migration

client:
  mono:
    auth-token: ${MONO_AUTH_TOKEN}
